# SQLite. Versions 3.8.0 and up are supported.
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem "sqlite3"
#
default: &default
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>

development:
  <<: *default
  adapter: sqlite3
  database: db/development.sqlite3
  timeout: 5000

test:
  <<: *default
  adapter: sqlite3
  database: db/test.sqlite3
  timeout: 5000

production:
  primary: &primary_production
    <<: *default
    adapter: postgresql
    url: <%= ENV["DATABASE_URL"] %>

  cache:
    <<: *primary_production
  queue:
    <<: *primary_production
